# Generated by ChatGPT on 2026-01-05
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_message_options_message_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed'), ('draft', 'Draft')], default='active', max_length=20),
        ),
    ]
