# Generated by Django 5.2.9 on 2026-01-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_message_options_message_deleted_at_and_more'),
        ('main', '0003_globalnotification'),
    ]

    operations = [
    ]
