# Generated by Django 5.2.9 on 2025-12-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_skill_level_alter_skill_name_alter_skill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('Full day', 'Full day'), ('Flexible schedule', 'Flexible schedule'), ('Shift work', 'Shift work')], default='Full day', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full time', 'Full time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Project work', 'Project work'), ('Volunteering', 'Volunteering')], default='Full time', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(default='Not specified', max_length=50),
        ),
    ]
