# Generated by Django 5.2.9 on 2026-01-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_job_status'),
        ('main', '0004_merge_20260105_1513'),
    ]

    operations = [
    ]
