# Generated by Django 5.2.9 on 2025-12-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_allow_contact_profile_email_notifications_and_more'),
        ('main', '0007_alter_skill_description_alter_skill_level_and_more'),
    ]

    operations = [
    ]
