# Generated by Django 5.2.9 on 2025-12-14 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_20251214_1808'),
        ('main', '0010_alter_skill_level_alter_skill_name_alter_skill_user'),
    ]

    operations = [
    ]
