# Generated by Django 5.2.9 on 2025-12-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_job_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('FULLTIME', 'Full time'), ('PARTTIME', 'Part-time'), ('INTERN', 'Internship'), ('CONTRACT', 'Project / Contract')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='working_schedule',
            field=models.CharField(blank=True, choices=[('full_day', 'Full day'), ('flexible', 'Flexible schedule'), ('shift', 'Shift work')], max_length=20, null=True),
        ),
    ]
