# Generated by Django 5.2.9 on 2025-12-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_job_employment_type_job_working_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillTag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.ManyToManyField(blank=True, related_name="jobs", to="main.skilltag"),
        ),
    ]
