# Generated by Django 5.2.9 on 2025-12-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_skilltag_and_job_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='article_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text Post'), ('photo', 'Photo Post'), ('video', 'Video Post'), ('article', 'Article')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='post_videos/'),
        ),
    ]
